name: rextrucks
favicon: null
layout_spectrum: 0.46135
typography_spectrum: 1
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: We trade with Used and New trucks of all brands and models.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#565553'
    - '#a4a5a7'
    - '#1c1c1c'
    - '#cbcac6'
  brandStrength: 0.3691756
  lightness: 0.6875
  saturation: 0.516129
  rhythmicContrast: 1
purpose: []
