name: rextrucks
favicon: null
layout_spectrum: 0.5836
typography_spectrum: 0.86186
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#565553'
    - '#a4a5a7'
    - '#1c1c1c'
    - '#cbcac6'
  brandStrength: 0.2687807746697217
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.9843682358041406
purpose: []
