name: rextrucks
favicon: null
layout_spectrum: 0.5394265
typography_spectrum: 1
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#17161E'
    - '#C7B39A'
    - '#A55B26'
    - '#667688'
  brandStrength: 0.3691756
  lightness: 0.6875
  saturation: 0.516129
  rhythmicContrast: 1
purpose: []
